### ISSUE TITLE
Undeclared Python dependency requests

### ISSUE THREAD

**Issue by rodrigobdz** [lkpsg/ccscanner#3]
## Issue

After following the instructions in the readme to start using this package, I encountered that the `requests` dependency is used in the package (see `submodule_extractor.py`) but is not declared as a dependency (see `requirements.txt`). 

https://github.com/lkpsg/ccscanner/blob/2299e3ebfac9f3811f1133f9801bda452188a792/ccscanner/extractors/submodule_extractor.py#L5

https://github.com/lkpsg/ccscanner/blob/0fc0c37dc354b0042d0140c3034622d829e292a3/ccscanner/requirements.txt#L1-L4

## Fix

Add `requests` to `requirements.txt`.

**Comment by lkpsg** [comment]
fixed
